name: Poll telegram bot on new messages
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types:
      - "on-demand-deploy"

jobs:
  start_poll_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: yarn

      - uses: ./.github/actions/stop-wait-concurrent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Start bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: yarn start
